// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package go_svr_proto_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/grpc-server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TokenService service

type TokenService interface {
	CreateToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error)
	DeleteToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error)
}

type tokenService struct {
	c    client.Client
	name string
}

func NewTokenService(name string, c client.Client) TokenService {
	return &tokenService{
		c:    c,
		name: name,
	}
}

func (c *tokenService) CreateToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.name, "TokenService.CreateToken", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenService) DeleteToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*TokenResponse, error) {
	req := c.c.NewRequest(c.name, "TokenService.DeleteToken", in)
	out := new(TokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenService service

type TokenServiceHandler interface {
	CreateToken(context.Context, *TokenRequest, *TokenResponse) error
	DeleteToken(context.Context, *TokenRequest, *TokenResponse) error
}

func RegisterTokenServiceHandler(s server.Server, hdlr TokenServiceHandler, opts ...server.HandlerOption) error {
	type tokenService interface {
		CreateToken(ctx context.Context, in *TokenRequest, out *TokenResponse) error
		DeleteToken(ctx context.Context, in *TokenRequest, out *TokenResponse) error
	}
	type TokenService struct {
		tokenService
	}
	h := &tokenServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TokenService{h}, opts...))
}

type tokenServiceHandler struct {
	TokenServiceHandler
}

func (h *tokenServiceHandler) CreateToken(ctx context.Context, in *TokenRequest, out *TokenResponse) error {
	return h.TokenServiceHandler.CreateToken(ctx, in, out)
}

func (h *tokenServiceHandler) DeleteToken(ctx context.Context, in *TokenRequest, out *TokenResponse) error {
	return h.TokenServiceHandler.DeleteToken(ctx, in, out)
}
