// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package go_svr_proto_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "go-micro/go-micro-part1-test01/web/proto/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Empno                int32    `protobuf:"varint,1,opt,name=empno,proto3" json:"empno,omitempty"`
	BirthDate            string   `protobuf:"bytes,2,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	HireDate             string   `protobuf:"bytes,6,opt,name=hireDate,proto3" json:"hireDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmpno() int32 {
	if m != nil {
		return m.Empno
	}
	return 0
}

func (m *Employee) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Employee) GetHireDate() string {
	if m != nil {
		return m.HireDate
	}
	return ""
}

type GetEmployeeRequest struct {
	BaseRequest          *common.BaseRequest `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	FirstName            string              `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetEmployeeRequest) Reset()         { *m = GetEmployeeRequest{} }
func (m *GetEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeRequest) ProtoMessage()    {}
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *GetEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeRequest.Unmarshal(m, b)
}
func (m *GetEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeRequest.Merge(m, src)
}
func (m *GetEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeRequest.Size(m)
}
func (m *GetEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeRequest proto.InternalMessageInfo

func (m *GetEmployeeRequest) GetBaseRequest() *common.BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *GetEmployeeRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type GetEmployeeResponse struct {
	BaseResponse         *common.BaseResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Employees            []*Employee          `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEmployeeResponse) Reset()         { *m = GetEmployeeResponse{} }
func (m *GetEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeResponse) ProtoMessage()    {}
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *GetEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeResponse.Unmarshal(m, b)
}
func (m *GetEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *GetEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeResponse.Merge(m, src)
}
func (m *GetEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeResponse.Size(m)
}
func (m *GetEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeResponse proto.InternalMessageInfo

func (m *GetEmployeeResponse) GetBaseResponse() *common.BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GetEmployeeResponse) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "go.svr.proto.proto.employee")
	proto.RegisterType((*GetEmployeeRequest)(nil), "go.svr.proto.proto.GetEmployeeRequest")
	proto.RegisterType((*GetEmployeeResponse)(nil), "go.svr.proto.proto.GetEmployeeResponse")
}

func init() {
	proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac)
}

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0x69, 0xff, 0x2d, 0xcd, 0xa4, 0x28, 0x4c, 0x8b, 0xac, 0xa1, 0x87, 0x90, 0x83,
	0xe6, 0xb4, 0x42, 0x44, 0x10, 0xcf, 0x8a, 0x37, 0x0f, 0xeb, 0x13, 0x24, 0x75, 0x6c, 0x03, 0x4d,
	0x36, 0xee, 0xae, 0x05, 0x9f, 0xc1, 0x57, 0xf1, 0x21, 0xa5, 0xd9, 0x4d, 0x9b, 0x58, 0xc1, 0x4b,
	0xe0, 0xdb, 0xdf, 0x37, 0x33, 0xdf, 0x4c, 0xe0, 0x84, 0xca, 0x7a, 0x23, 0x3f, 0x88, 0x78, 0xad,
	0xa4, 0x91, 0x88, 0x2b, 0xc9, 0xf5, 0x56, 0x59, 0x65, 0xbf, 0x21, 0x5b, 0xca, 0xb2, 0x94, 0xd5,
	0x55, 0x9e, 0x69, 0x12, 0xf4, 0xf6, 0x4e, 0xda, 0x38, 0x72, 0xde, 0x23, 0xba, 0x96, 0x95, 0x76,
	0x8d, 0xe2, 0x2f, 0x0f, 0x26, 0x6d, 0x6f, 0x9c, 0xc3, 0x88, 0xca, 0xba, 0x92, 0xcc, 0x8b, 0xbc,
	0x64, 0x24, 0xac, 0xc0, 0x05, 0xf8, 0x79, 0xa1, 0xcc, 0xfa, 0x3e, 0x33, 0xc4, 0x06, 0x91, 0x97,
	0xf8, 0xe2, 0xf0, 0xb0, 0xa3, 0xaf, 0x85, 0xd2, 0xe6, 0x29, 0x2b, 0x89, 0x0d, 0x2d, 0xdd, 0x3f,
	0x60, 0x08, 0x93, 0x4d, 0xe6, 0xe0, 0xff, 0x06, 0xee, 0x35, 0x9e, 0xc1, 0x78, 0x45, 0xd5, 0x0b,
	0x29, 0x36, 0x6a, 0x88, 0x53, 0xbb, 0x9a, 0x75, 0xa1, 0xa8, 0x19, 0x37, 0xb6, 0x35, 0xad, 0x8e,
	0x0b, 0xc0, 0x47, 0x32, 0x0f, 0x2e, 0xb0, 0xdb, 0x12, 0x6f, 0x20, 0xe8, 0x2c, 0xdd, 0xa4, 0x0f,
	0xd2, 0x19, 0xb7, 0x5b, 0xf3, 0x0e, 0x12, 0x5d, 0x5f, 0x3f, 0xfa, 0xe0, 0x47, 0xf4, 0xf8, 0xd3,
	0x83, 0x59, 0x6f, 0x96, 0xbd, 0x1b, 0xde, 0xc2, 0xb4, 0x7b, 0x47, 0x37, 0x6d, 0xde, 0x9f, 0x66,
	0x99, 0xe8, 0x39, 0xf1, 0x0e, 0xfc, 0xf6, 0xd4, 0x9a, 0x0d, 0xa2, 0x61, 0x12, 0xa4, 0x0b, 0x7e,
	0xfc, 0x23, 0x79, 0x6b, 0x12, 0x07, 0x7b, 0x6a, 0xe0, 0xb4, 0x4d, 0xf2, 0x4c, 0x6a, 0x5b, 0x2c,
	0x09, 0x33, 0x98, 0x76, 0xf2, 0x69, 0xbc, 0xf8, 0xad, 0xd7, 0xf1, 0xb5, 0xc2, 0xcb, 0x3f, 0x7d,
	0x36, 0x6f, 0xfc, 0x2f, 0x1f, 0x37, 0xf0, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xcb, 0xc5,
	0x89, 0x7f, 0x02, 0x00, 0x00,
}
