// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package go_svr_proto_proto

import (
	common "go-micro/go-micro-part03/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenRequest struct {
	BaseRequest          *common.BaseRequest `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	UserId               uint64              `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string              `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Token                string              `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetBaseRequest() *common.BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *TokenRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenResponse struct {
	BaseResponse         *common.BaseResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Token                string               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetBaseResponse() *common.BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenRequest)(nil), "go.svr.proto.proto.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "go.svr.proto.proto.TokenResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x35, 0x6d, 0x2d, 0x75, 0xb6, 0x5e, 0xc6, 0x22, 0x71, 0x4f, 0xeb, 0x9e, 0xf6, 0x14, 0xa1,
	0x22, 0x78, 0x57, 0x10, 0x2f, 0x82, 0xb1, 0x77, 0xd9, 0xd6, 0x41, 0x45, 0x77, 0x53, 0x93, 0x6c,
	0xff, 0x42, 0xfc, 0x65, 0xd9, 0x9d, 0xa0, 0x59, 0x04, 0x4f, 0x7b, 0x09, 0x79, 0xf3, 0x5e, 0xde,
	0x7b, 0x19, 0x80, 0xb2, 0xf1, 0x2f, 0x6a, 0x6b, 0x8d, 0x37, 0x88, 0xcf, 0x46, 0xb9, 0x9d, 0x65,
	0xc4, 0x67, 0x2a, 0x37, 0xa6, 0xaa, 0x4c, 0x7d, 0xb6, 0x2e, 0x1d, 0x69, 0xfa, 0x68, 0xc8, 0xf9,
	0xc0, 0x9c, 0xf4, 0x18, 0xb7, 0x35, 0xb5, 0x23, 0xa6, 0xf2, 0x2f, 0x01, 0xf3, 0x95, 0x79, 0xa3,
	0x3a, 0xbc, 0xc0, 0x0b, 0x48, 0x22, 0x03, 0x29, 0x32, 0x51, 0x24, 0xcb, 0x23, 0xc5, 0x0e, 0x2a,
	0xa2, 0x74, 0xac, 0xc3, 0x63, 0x98, 0x36, 0x8e, 0xec, 0xed, 0x93, 0x1c, 0x65, 0xa2, 0x98, 0xe8,
	0x80, 0x30, 0x85, 0x59, 0x7b, 0xbb, 0x2b, 0x2b, 0x92, 0xe3, 0x4c, 0x14, 0x07, 0xfa, 0x07, 0xe3,
	0x02, 0xf6, 0x7d, 0x1b, 0x2d, 0x27, 0x1d, 0xc1, 0x20, 0x7f, 0x84, 0xc3, 0x50, 0x88, 0x8b, 0xe2,
	0x25, 0xcc, 0xe3, 0xe2, 0xa1, 0xd2, 0xa2, 0x5f, 0x89, 0x39, 0xdd, 0x53, 0xfe, 0x06, 0x8c, 0xa3,
	0x80, 0xe5, 0xe7, 0x28, 0x7c, 0xf9, 0x81, 0xec, 0xee, 0x75, 0x43, 0xb8, 0x82, 0xe4, 0xca, 0x52,
	0xe9, 0xa9, 0x9b, 0x62, 0xa6, 0xfe, 0x2e, 0x57, 0xc5, 0x3b, 0x4a, 0x4f, 0xff, 0x51, 0x70, 0x74,
	0xbe, 0xd7, 0xba, 0x5e, 0xd3, 0x3b, 0x0d, 0xec, 0x7a, 0x0f, 0xb3, 0x1b, 0xf2, 0x43, 0x5a, 0xae,
	0xa7, 0xdd, 0xf8, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xf5, 0xc8, 0xff, 0x60, 0x02, 0x00,
	0x00,
}
