// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package go_svr_proto_proto

import (
	common "go-micro/go-micro-part03/proto/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Empno                int32    `protobuf:"varint,1,opt,name=empno,proto3" json:"empno,omitempty"`
	BirthDate            string   `protobuf:"bytes,2,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	HireDate             string   `protobuf:"bytes,6,opt,name=hireDate,proto3" json:"hireDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmpno() int32 {
	if m != nil {
		return m.Empno
	}
	return 0
}

func (m *Employee) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Employee) GetHireDate() string {
	if m != nil {
		return m.HireDate
	}
	return ""
}

type LoginRequest struct {
	BaseRequest          *common.BaseRequest `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	FirstName            string              `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Token                string              `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetBaseRequest() *common.BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *LoginRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	BaseResponse         *common.BaseResponse `protobuf:"bytes,5,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Employee             *Employee            `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	Token                string               `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetBaseResponse() *common.BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *LoginResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	BaseRequest          *common.BaseRequest `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	Token                string              `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{3}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetBaseRequest() *common.BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	BaseResponse         *common.BaseResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{4}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetBaseResponse() *common.BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

type GetEmployeeRequest struct {
	BaseRequest          *common.BaseRequest `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	FirstName            string              `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetEmployeeRequest) Reset()         { *m = GetEmployeeRequest{} }
func (m *GetEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeRequest) ProtoMessage()    {}
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{5}
}

func (m *GetEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeRequest.Unmarshal(m, b)
}
func (m *GetEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeRequest.Merge(m, src)
}
func (m *GetEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeRequest.Size(m)
}
func (m *GetEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeRequest proto.InternalMessageInfo

func (m *GetEmployeeRequest) GetBaseRequest() *common.BaseRequest {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *GetEmployeeRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type GetEmployeeResponse struct {
	BaseResponse         *common.BaseResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Employees            []*Employee          `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEmployeeResponse) Reset()         { *m = GetEmployeeResponse{} }
func (m *GetEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeResponse) ProtoMessage()    {}
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{6}
}

func (m *GetEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeResponse.Unmarshal(m, b)
}
func (m *GetEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *GetEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeResponse.Merge(m, src)
}
func (m *GetEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeResponse.Size(m)
}
func (m *GetEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeResponse proto.InternalMessageInfo

func (m *GetEmployeeResponse) GetBaseResponse() *common.BaseResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *GetEmployeeResponse) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "go.svr.proto.proto.employee")
	proto.RegisterType((*LoginRequest)(nil), "go.svr.proto.proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.svr.proto.proto.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "go.svr.proto.proto.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "go.svr.proto.proto.LogoutResponse")
	proto.RegisterType((*GetEmployeeRequest)(nil), "go.svr.proto.proto.GetEmployeeRequest")
	proto.RegisterType((*GetEmployeeResponse)(nil), "go.svr.proto.proto.GetEmployeeResponse")
}

func init() {
	proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac)
}

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0x35, 0xa9, 0x09, 0xed, 0x6d, 0xad, 0x70, 0x5b, 0x24, 0x86, 0x2e, 0x62, 0x16, 0xda, 0x55,
	0x84, 0x8a, 0x50, 0x5c, 0x2b, 0x82, 0x48, 0xc1, 0xb8, 0x75, 0x93, 0xd6, 0x6b, 0x1b, 0x6c, 0x32,
	0x31, 0x33, 0x2d, 0xf4, 0x19, 0x7c, 0x00, 0xf1, 0x1d, 0x7c, 0x48, 0xe9, 0xfc, 0x34, 0xc9, 0xd7,
	0xbf, 0x0f, 0xca, 0xb7, 0x09, 0xdc, 0x39, 0x67, 0xce, 0x3d, 0xe7, 0xde, 0x09, 0xf4, 0x29, 0x2b,
	0xd6, 0x6c, 0x47, 0x14, 0x15, 0x25, 0x13, 0x0c, 0x71, 0xc9, 0x22, 0xbe, 0x2d, 0x55, 0xa5, 0xbe,
	0xbe, 0xb7, 0x60, 0x59, 0xc6, 0xf2, 0xd7, 0xf3, 0x84, 0x53, 0x4c, 0xbf, 0x36, 0xc4, 0x85, 0x46,
	0x9e, 0x37, 0x10, 0x5e, 0xb0, 0x9c, 0x6b, 0xa1, 0xf0, 0x9f, 0x05, 0x6d, 0xa3, 0x8d, 0x43, 0x70,
	0x28, 0x2b, 0x72, 0xe6, 0x59, 0x81, 0x35, 0x76, 0x62, 0x55, 0xe0, 0x08, 0x3a, 0xf3, 0xb4, 0x14,
	0xab, 0xf7, 0x89, 0x20, 0xcf, 0x0e, 0xac, 0x71, 0x27, 0xae, 0x0e, 0xf6, 0xe8, 0x8f, 0xb4, 0xe4,
	0x62, 0x96, 0x64, 0xe4, 0xb5, 0x14, 0x7a, 0x38, 0x40, 0x1f, 0xda, 0xeb, 0x44, 0x83, 0x8f, 0x25,
	0x78, 0xa8, 0xf1, 0x19, 0xb8, 0x4b, 0xca, 0xbf, 0x53, 0xe9, 0x39, 0x12, 0xd1, 0xd5, 0xfe, 0xce,
	0x2a, 0x2d, 0x49, 0xb6, 0x73, 0xd5, 0x1d, 0x53, 0x87, 0x3b, 0xe8, 0x7d, 0x66, 0xcb, 0x34, 0xd7,
	0xf9, 0xf0, 0x2d, 0x74, 0x6b, 0x71, 0xa5, 0xef, 0xee, 0x64, 0x10, 0xa9, 0xbc, 0x51, 0x0d, 0x8a,
	0xeb, 0xbc, 0xa6, 0x69, 0xfb, 0xae, 0xe9, 0x21, 0x38, 0x82, 0xfd, 0xa4, 0x5c, 0xc7, 0x51, 0x45,
	0xf8, 0xd7, 0x82, 0x27, 0xba, 0xb7, 0x9a, 0x20, 0x4e, 0xa1, 0x57, 0x9f, 0xa8, 0x8c, 0xd1, 0x9d,
	0x0c, 0x9b, 0xdd, 0x15, 0x16, 0x37, 0x98, 0x38, 0xad, 0x86, 0xae, 0x3d, 0x8f, 0xa2, 0xe3, 0x8d,
	0x46, 0x86, 0x13, 0x37, 0x56, 0xa4, 0xbc, 0xd9, 0x75, 0x6f, 0xdf, 0xa4, 0x35, 0xb6, 0x11, 0x37,
	0xce, 0xe5, 0xb4, 0xfa, 0x27, 0xe8, 0x1b, 0xf5, 0x33, 0xc9, 0xad, 0xfb, 0x26, 0x0f, 0x53, 0xc0,
	0x8f, 0x24, 0x3e, 0x98, 0x60, 0x0f, 0xb8, 0xc6, 0xf0, 0xb7, 0x05, 0x83, 0x46, 0xaf, 0x5b, 0xcd,
	0xe3, 0x3b, 0xe8, 0x98, 0x45, 0x70, 0xcf, 0x0e, 0x5a, 0x57, 0xf7, 0x56, 0xd1, 0x27, 0x7f, 0x6c,
	0x78, 0x6a, 0xac, 0x7c, 0xa5, 0x72, 0x9b, 0x2e, 0x08, 0x13, 0xe8, 0xd5, 0x0c, 0x72, 0x7c, 0x79,
	0x4a, 0xec, 0x78, 0x5c, 0xfe, 0xab, 0xab, 0x3c, 0x3d, 0xed, 0x47, 0x38, 0x03, 0x47, 0x3e, 0x5a,
	0x0c, 0x4e, 0xdd, 0xa9, 0xff, 0x4b, 0xfe, 0x8b, 0x0b, 0x8c, 0x83, 0xde, 0x17, 0x70, 0xd5, 0x5b,
	0xc0, 0x73, 0xf4, 0xea, 0x15, 0xfa, 0xe1, 0x25, 0x8a, 0x91, 0x9c, 0xbb, 0xf2, 0xfc, 0xcd, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0xd7, 0x5e, 0x3f, 0xe4, 0x04, 0x00, 0x00,
}
